### ISSUE TITLE
ssr下有些内容在查看网页源代码下没显示出来

### ISSUE THREAD

**Issue by suiyi8760** [alexayan/express-dva-ssr#10]
初次接触ssr，打开连接页面显示正常，查看网页源码有部分内容没显示，一般有什么原因会造成这种情况？

**Comment by alexayan** [comment]
在 express-dva-ssr 中, 会根据 dva model 中的 effects 来判断是否是异步渲染。
因此异常数据请求需要在 effects 中进行。否则服务器端渲染会在异步数据请求前直接渲染，这会造成没内容的情况。

**Comment by suiyi8760** [comment]
好的，不过我现在发现我这问题是用了ant-motion的分屏动画导致的，就是滚动到一定位置才显示对应的dom内容，而ssr没能把这些读出来，如果考虑seo有没有什么比较好的办法处理

**Comment by alexayan** [comment]
代码中区分下服务器端和客户端。

**Comment by suiyi8760** [comment]
针对不同端渲染不同html的意思么？在server.js中判断ua吗还是有办法在react组件中判断，劳烦大佬具体指点下😂

**Comment by alexayan** [comment]
typeof window === 'undefined' ? 'server' : 'browser'

**Comment by suiyi8760** [comment]
万分感谢！居然没想起这方法，总算搞定了
