### ISSUE TITLE
删除dva的model中的subscriptions定义后加载不了页面

### ISSUE THREAD

**Issue by xhubert** [alexayan/express-dva-ssr#4]
__express-dva-ssr@v0.2.0__

场景是这样的，`dva`的某个`model`定义如下：
```javascript
// topic model
...
  subscriptions: {
     setup({ dispatch }) {
       dispatch({
         type: 'fetchTopics',
       });
     },
  },
...
```
如果把这段代码注释掉，或者删掉，则页面一直处于加载中。
`ssr middleware`的定义如下：
```javascript
// ssr middleware
...
const ssrRender = ssr.runtimeSSRMiddle({
  routes,
  createApp,
  initialState: {}, // custom initialState
  renderFullPage,
  onRenderSuccess,
});

// const preSsrRender = () => ssr.preSSRService({
//   interval: 10000, // render interval
//   routes,
//   createApp,
//   initialState: {}, // custom initialState
//   asyncActions: ['topic/fetchTopics'], // async actions in dva
//   renderFullPage,
//   onRenderSuccess,
// });

export {
  ssrRender as default,
  // preSsrRender,
};
```

**Comment by alexayan** [comment]
@idpocky  没有足够的信息。
你在 `effects` 中定义了 fetchTopics 吗？
在 `fetchTopics` 加 `try catch` 或调试信息，看是否代码执行失败

**Comment by pigongting** [comment]
今天刚看到这个包，不知道怎么用啊，有没有demo呢？

**Comment by alexayan** [comment]
@pigongting  明天我加个 demo 吧

**Comment by pigongting** [comment]
非常感谢，期待

**Comment by alexayan** [comment]
@pigongting DEMO [dva-example-user-dashboard-ssr](https://github.com/alexayan/dva-example-user-dashboard-ssr)

**Comment by pigongting** [comment]
@alexayan 非常感谢

**Comment by pigongting** [comment]
@alexayan 非常非常感谢，如果使用 antd-mobile 是否会有问题呢？

**Comment by alexayan** [comment]
@pigongting 没有问题。

`express-dva-ssr` 会在初始 `initState` 中注入 `app.SSR_ENV.platform`。对于移动端请求，值为 `mobile`。 PC 端请求，值为 `pc`。

因此在你的代码中，可能需要根据 `state.app.SSR_ENV` 进行相应的渲染。

**Comment by pigongting** [comment]
@alexayan 我尝试使用 antd-mobile 的组件，服务端渲染的时候会报错：

Unexpected key "app" found in preloadedState argument passed to createStore. Expected to find one of the known reducer keys instead: "routing", "users", "@@dva". Unexpected keys will be ignored.
Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in. Check the render method of `IndexPage
`.

**Comment by xhubert** [comment]
@pigongting 我消灭这个`warning`的方法是在`createApp`的时候初始化一下`app`这个`model`。

```javascript
...
  // 2. Model
  app.model({
    namespace: 'app',
    state: initialState.app,
  });
...
```

**Comment by xhubert** [comment]
@alexayan `fetchTopics`这个`effect`肯定是定义了的。

改天我再看看你的`demo`，然后再去定位问题。

**Comment by alexayan** [comment]
@idpocky 版本升级到 `0.2.3` 试试

**Comment by pigongting** [comment]
@alexayan 我尝试使用 antd-mobile 的组件，服务端渲染的时候会报错，也看到 https://github.com/ant-design/ant-design-mobile/issues/775 有提到，是因为antd-mobile的组件不支持服务端渲染吗？
`.

**Comment by pigongting** [comment]
@alexayan @idpocky 我尝试使用 antd-mobile 的组件，服务端渲染的时候会报错，也看到 ant-design/ant-design-mobile#775 有提到，是因为antd-mobile的组件不支持服务端渲染吗？

**Comment by pigongting** [comment]
@idpocky @alexayan 打扰了，使用这种方式不会报错：
import Button from 'antd-mobile/lib/button/index.web.js';

**Comment by xhubert** [comment]
@pigongting 我暂时还没有尝试过`antd-mobile`。
