### ISSUE TITLE
客户端会重复渲染？

### ISSUE THREAD

**Issue by pigongting** [alexayan/express-dva-ssr#5]
在 https://github.com/alexayan/dva-example-user-dashboard-ssr Demo 中，执行 node server/index.js 后，访问 http://localhost:9090/users，在 Console 中会显示：
Fetch finished loading: GET "http://jsonplaceholder.typicode.com/users?_page=1&_limit=3".

这是否表示客户端重复渲染了？

**Comment by alexayan** [comment]
@pigongting 重复渲染可以在 `dva-example-user-dashboard-ssr` 代码中进行优化，与 `express-dva-ssr` 无关。
