### ISSUE TITLE
求助，initialState

### ISSUE THREAD

**Issue by forever4313** [alexayan/express-dva-ssr#7]
在demo中，initialState 里面设置的是users为空数组[],而在浏览器进行请求的时候，返回的源码中发现users里面有值呢，是在什么地方请求的，没发现。

**Comment by alexayan** [comment]
@forever4313  
https://github.com/alexayan/dva-example-user-dashboard-ssr/blob/master/src/models/users.js#L58 服务器端请求，并渲染。

**Comment by forever4313** [comment]
@alexayan  可以加一下联系方式吗？你指出的 地方我看过，我调用到了，服务器也打印出来了，但是前端拿到的渲染页面state是没有值的，好尴尬

在reducers 里我update了state，然后我也能取出来，但是，貌似这个state 没有进入到渲染阶段，还是我在runtimeSSRMiddle里设置的初始值，找不到为什么
求指导

**Comment by alexayan** [comment]
@forever4313 
我本地测试应该是没问题的(代码缺少判断是否已经服务器请求了数据，导致在客服端进行了重复的请求)
可以通过邮件联系 yanhaibiao1991@gmail.com

**Comment by forever4313** [comment]
@alexayan 原来有个sync

**Comment by forever4313** [comment]
@alexayan  可以问一下，怎么判断是后台还是前台吗

**Comment by alexayan** [comment]
@forever4313
 `componentWillMount()` 在服务器端运行。`typeof window === 'undefined'` 可以判断是否是服务器端。
